# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: c43162a
_src_path: gh:scipp/copier_template
description: SANS data reduction for the European Spallation Source
max_python: '3.12'
min_python: '3.8'
nightly_deps: plopp,sciline,scippneutron
orgname: scipp
projectname: esssans
year: 2023
